export default {
	products: [
		{
			_id: '123',
			category: 'Shirts',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'some brand',
			rating: 4.5,
			numReviews: 10,
		},
		{
			_id: '124',
			category: 'Shirts',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 60,
			brand: 'some brand',
			rating: 4.5,
			numReviews: 10,
		},
		{
			_id: '125',
			category: 'Shirts',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 40,
			brand: 'some brand',
			rating: 2.0,
			numReviews: 10,
		},
		{
			_id: '126',
			category: 'Shirts',
			name: 'Slim Shirt',
			image: '/images/d1.jpg',
			price: 10,
			brand: 'some brand',
			rating: 4.5,
			numReviews: 10,
		},
	],
};
